ParseCommandLine: Add Command for Muting Audio
mpc-hc/mpc-hc pull request #175
Opened 2017-03-24 23:16 UTC by precla

Feature request trac: #5657
Add 'mute' switch to launch File with muted Audio.

2017-03-29 00:03 UTC, kasper93 commented on src/mpc-hc/AppSettings.cpp
> +            } else if (sw == _T("mute")){
Why add here? Keep some sane order. Probably end will be good to make it roughly follow enum order.

2017-03-29 00:03 UTC, kasper93 commented on src/mpc-hc/MainFrm.cpp
> +    if (AfxGetAppSettings().nCLSwitches & CLSW_MUTE) {
Probably should be before put_Volume. Also `OpenSetupAudio()` is called when starting playback. I think it should set volume not only in this case. That say probably better place to set vol is when restoring setting. https://github.comhttps://github.com/mpc-hc/mpc-hc/blob/develop/src/mpc-hc/AppSettings.cpp#L760

(simply set fMute when parsing cmdline)

2017-03-29 21:05 UTC, precla commented on src/mpc-hc/MainFrm.cpp
> +    if (AfxGetAppSettings().nCLSwitches & CLSW_MUTE) {
That is in SaveSettings() , do you mean LoadSettings() ?

2017-03-29 21:06 UTC, precla commented on src/mpc-hc/AppSettings.cpp
> +            } else if (sw == _T("mute")){
Changed order

2017-07-18 22:39 UTC, matthewmauger requested changes
Generally fine but this will now clash with recent changes as there is a new resource entry with the same ID as yours. Can you fix this, put yours in the proper location and resubmit?

2017-07-21 17:35 UTC, precla commented
Close this mumbo-jubmo.. Made a new clean one: https://github.com/mpc-hc/mpc-hc/pull/184

2017-07-21 17:35 UTC, closed without merging