ParseCommandLine: Add Command for View Preset
mpc-hc/mpc-hc pull request #177
Opened 2017-03-26 22:50 UTC by precla

Feature request trac: #5539
Add 'viewpreset' switch to launch MPC-HC with one of the 3 Presets
1 -> minimal
2 -> compact
3 -> normal

2017-03-26 23:30 UTC, XhmikosR commented
All this are nice, but they aren't added to the help dialog so it's basically hidden.

Not sure we want to bloat the dialog more, though.

2017-03-27 18:04 UTC, precla commented
Yeah, quite a bunch of command switches already there (cl dialog).
Adding them wouldn't be a problem, but do we want to add them there?
Maybe we should clean up the Feature requests on trac before we move on with such things.
Maybe see what others think of more cl switches?

2017-03-29 00:05 UTC, kasper93 commented
>  Adding them wouldn't be a problem, but do we want to add them there?

Sure. There is literary no point in adding command line switches if we don't have them documented anywhere. Command line help is not perfect, but it can hold more options.

2017-03-29 20:25 UTC, precla commented
Added into CL Help dialog

2017-07-18 22:22 UTC, matthewmauger approved these changes
Looks good to me! Only issue is whitespace differences which looks like it's causing a conflict.

2017-07-18 22:27 UTC, matthewmauger requested changes
Ok looks like this is not going to go in without a merge - can you pull develop, merge into your branch fixing the clash in src/mpc-hc/resource.h and resubmit?

Edit: Just noticed that your resource entries are also out of date. You're going to need to pull latest, update your string - fix the carriage returns or whatever is making the diff fail - and resubmit. At the moment we're going to have a clash due to duplicate IDs. This is also an issue with your other pull requests which create different entries but all of which use the same ID (57535)

2017-07-19 18:02 UTC, precla commented
I'll have a look into it in the next few days.

2017-07-20 16:22 UTC, XhmikosR commented on src/mpc-hc/resource.h
> +<<<<<<< HEAD
This is definitely wrong :P

2017-07-20 17:10 UTC, precla commented
@matthewmauger Everything done for this. Thanks to @XhmikosR 
Should be ok now. Can you check please?

2017-07-20 22:10 UTC, matthewmauger approved these changes
Looks good to me! Thanks for fixing that up. Approved.

2017-07-30 18:08 UTC, closed without merging

2017-07-30 18:08 UTC, kasper93 commented
Thanks!